spring.application.name=PaymentService
stripe.apiKey=${MYSTORE_STRIPE_APIKEY}
server.port=${MYSTORE_PAYMENT_SERVICE_PORT}
mystore.admin.frontend.url=${MYSTORE_ADMIN_FRONTEND_UR}
mystore.user.frontend.url=${MYSTORE_USER_FRONTEND_URL}
mystore.product.service.url=${MYSQL_PRODUCT_SERVICE_URL}